runtime: nodejs20
env: standard
instance_class: F1

# Environment variables MUST be set via Google Cloud Console
# Go to: App Engine > Settings > Environment Variables
# Required variables:
#   - JWT_SECRET
#   - GEMINI_API_KEY (optional, for AI features)
#   - OPENAI_API_KEY (optional, for AI features)